

function classColorsCodes()
{
    var out = [
<<<<<<< HEAD

        {className: 'n12_Tac1/Epha3_12', IdentifiedType: ' n12_Tac1/Epha3_12', color: '#3A19BD'},
        {className: 'n03_Tac1/Abi3bp_3', IdentifiedType: ' n03_Tac1/Abi3bp_3', color: '#3A19BD'},
        {className: 'n08_Col11a1/Nfib_8', IdentifiedType: ' n08_Col11a1/Nfib_8', color: '#3A19BD'},
        {className: 'n17_Pcdh15/Tcf4_17', IdentifiedType: ' n17_Pcdh15/Tcf4_17', color: '#3DCCFF'},
        {className: 'n00_Pam/Nnat_0', IdentifiedType: ' n00_Pam/Nnat_0', color: '#7757FA'},
        {className: 'n05_Zfp804b_5', IdentifiedType: ' n05_Zfp804b_5', color: '#7757FA'},
        {className: 'n04_Gpc5_4', IdentifiedType: ' n04_Gpc5_4', color: '#5938DB'},
        {className: 'n06_Chst9/Zfhx3_6', IdentifiedType: ' n06_Chst9/Zfhx3_6', color: '#5938DB'},
        {className: 'n27_4931429P17Rik/Cdh23_27', IdentifiedType: ' n27_4931429P17Rik/Cdh23_27', color: '#FF0000'},
        {className: 'n20_Adarb2/Epha3_20', IdentifiedType: ' n20_Adarb2/Epha3_20', color: '#FF0000'},
        {className: 'n29_Gm11867/Naaladl2_29', IdentifiedType: ' n29_Gm11867/Naaladl2_29', color: '#FF0000'},
        {className: 'n19_Pde11a_19', IdentifiedType: ' n19_Pde11a_19', color: '#FF0000'},
        {className: 'n10_Penk/Col9a1_10', IdentifiedType: ' n10_Penk/Col9a1_10', color: '#996E00'},
        {className: 'n25_Il1rapl2_25', IdentifiedType: ' n25_Il1rapl2_25', color: '#996E00'},
        {className: 'n13_Sst_13', IdentifiedType: ' n13_Sst_13', color: '#996E00'},
        {className: 'n28_Col11a1/Zfhx3_28', IdentifiedType: ' n28_Col11a1/Zfhx3_28', color: '#996E00'},
        {className: 'n01_Foxp2/Cck_1', IdentifiedType: ' n01_Foxp2/Cck_1', color: '#996E00'},
        {className: 'n02_Hmcn1/Cartpt_2', IdentifiedType: ' n02_Hmcn1/Cartpt_2', color: '#FF0000'},
        {className: 'n11_Ntng1/Vav3_11', IdentifiedType: ' n11_Ntng1/Vav3_11', color: '#FF0000'},
        {className: 'n07_Gm32647_7', IdentifiedType: ' n07_Gm32647_7', color: '#FF0000'},
        {className: 'n18_Nefm/Rreb1_18', IdentifiedType: ' n18_Nefm/Rreb1_18', color: '#996E00'},
        {className: 'n33_Prph/Piezo2_33', IdentifiedType: ' n33_Prph/Piezo2_33', color: '#FF00E6'},
        {className: 'n15_Calca/Pou6f2_15', IdentifiedType: ' n15_Calca/Pou6f2_15', color: '#FF00E6'},
        {className: 'n26_Gm28526_26', IdentifiedType: ' n26_Gm28526_26', color: '#FF00E6'},
        {className: 'n14_Hcn1_14', IdentifiedType: ' n14_Hcn1_14', color: '#1FADEB'},
        {className: 'n16_Cpne9/Col27a1_16', IdentifiedType: ' n16_Cpne9/Col27a1_16', color: '#1FADEB'},
        {className: 'n09_Adarb2/Prlr_9', IdentifiedType: ' n09_Adarb2/Prlr_9', color: '#1FADEB'},
        {className: 'n21_Ttn_21', IdentifiedType: ' n21_Ttn_21', color: '#1FADEB'},
        {className: 'n22_Slc32a1/Foxp2_22', IdentifiedType: ' n22_Slc32a1/Foxp2_22', color: '#BDA800'},
        {className: 'n31_Nps/Qrfpr_31', IdentifiedType: ' n31_Nps/Qrfpr_31', color: '#BDA800'},
        {className: 'n24_Slc18a2/Th_24', IdentifiedType: ' n24_Slc18a2/Th_24', color: '#BDA800'},
        {className: 'n23_Slc5a7/Chat_23', IdentifiedType: ' n23_Slc5a7/Chat_23', color: '#FAE52E'},
        {className: 'n32_Tnc/Rreb1_32', IdentifiedType: ' n32_Tnc/Rreb1_32', color: '#FAE52E'},
        {className: 'n30_Nts/Col5a2_30', IdentifiedType: ' n30_Nts/Col5a2_30', color: '#DBC70F'},
        // {className: 'TEGLU4', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'TEGLU22', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'TEGLU23', IdentifiedType: ' Ivy', color: '#994D91'},
        // {className: 'TEGLU24', IdentifiedType: ' MGE NGF', color: '#994D91'},
        // {className: 'TEGLU17', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        // {className: 'TEGLU18', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU19', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU14', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU13', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU21', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU10', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU11', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU20', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU12', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU9', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU8', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEINH10', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEINH11', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEINH12', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEINH9', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'OBINH5', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'TEINH5', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'TEINH6', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'TEINH7', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'TEINH8', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'TEINH4', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'TEINH20', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'TEINH13', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'TEINH14', IdentifiedType: ' PC Other1', color: '#73E500'},
        // {className: 'TEINH16', IdentifiedType: ' PC Other2', color: '#73E500'},
        // {className: 'TEINH15', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        // {className: 'TEINH19', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        // {className: 'TEINH21', IdentifiedType: ' Trilaminar', color: '#1F663B'},
        // {className: 'HYPEP7', IdentifiedType: ' Unidentified', color: '#A6A6A6'},
        // {className: 'HYPEP6', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'DEINH8', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'MBDOP1', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'MBDOP2', IdentifiedType: ' Backprojection', color: '#3DCCFF'},
        // {className: 'MEGLU14', IdentifiedType: ' Basket', color: '#7757FA'},
        // {className: 'MEGLU11', IdentifiedType: ' Basket', color: '#7757FA'},
        // {className: 'MEGLU10', IdentifiedType: ' Bistratified', color: '#5938DB'},
        // {className: 'MEGLU9', IdentifiedType: ' Bistratified', color: '#5938DB'},
        // {className: 'MEGLU8', IdentifiedType: ' Cck Calb1/Slc17a8*', color: '#FF0000'},
        // {className: 'MEGLU7', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'MEGLU6', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'DEGLU5', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'MEGLU2', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'MEGLU3', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'MEGLU1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'MEGLU5', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'MEGLU4', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'DEGLU4', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'DEGLU3', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'OBNBL1', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'MBCHO1', IdentifiedType: ' Cck Vip Cxcl14+', color: '#996E00'},
        // {className: 'HBGLU9', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'SCGLU1', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'HBGLU10', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'SCGLU10', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'HBGLU2', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'HBGLU3', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'HBNOR', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'HBGLU1', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'DEGLU2', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'DEGLU1', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'MSN1', IdentifiedType: ' IS2', color: '#FAE52E'},
        // {className: 'MSN2', IdentifiedType: ' IS2', color: '#FAE52E'},
        // {className: 'MSN3', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'MSN5', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'MSN4', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'MSN6', IdentifiedType: ' Ivy', color: '#994D91'},
        // {className: 'OEC', IdentifiedType: ' MGE NGF', color: '#994D91'},
        // {className: 'DETPH', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        // {className: 'RGDG', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'RGSZ', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'OPC', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SZNBL', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'EPMB', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'HYPEN', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'OBDOP2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'OBINH2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'OBINH3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'OBINH1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'OBINH4', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'OBNBL2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'TEGLU1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'DGGRC2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'DGGRC1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'DGNBL1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'DGNBL2', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'OBNBL3', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'HYPEP3', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'HYPEP2', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'HYPEP1', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'CBNBL2', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'CBGRC', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'CR', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'CBNBL1', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'SEPNBL', IdentifiedType: ' PC Other1', color: '#73E500'},
        // {className: 'OBNBL5', IdentifiedType: ' PC Other2', color: '#73E500'},
        // {className: 'OBNBL4', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        // {className: 'DECHO2', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        // {className: 'HYPEP5', IdentifiedType: ' Trilaminar', color: '#1F663B'},
        // {className: 'DEINH7', IdentifiedType: ' Unidentified', color: '#A6A6A6'},
        // {className: 'HYPEP4', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'HBGLU8', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'HBGLU6', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'HBGLU7', IdentifiedType: ' Backprojection', color: '#3DCCFF'},
        // {className: 'HBGLU5', IdentifiedType: ' Basket', color: '#7757FA'},
        // {className: 'HBGLU4', IdentifiedType: ' Basket', color: '#7757FA'},
        // {className: 'HBCHO2', IdentifiedType: ' Bistratified', color: '#5938DB'},
        // {className: 'HBCHO1', IdentifiedType: ' Bistratified', color: '#5938DB'},
        // {className: 'HBCHO3', IdentifiedType: ' Cck Calb1/Slc17a8*', color: '#FF0000'},
        // {className: 'HBADR', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'HBCHO4', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'TECHO', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'DECHO1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'SCINH1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'HBINH8', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'HBINH7', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'HBINH5', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'CBINH2', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'CBPC', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'CBINH1', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'MEINH1', IdentifiedType: ' Cck Vip Cxcl14+', color: '#996E00'},
        // {className: 'TEINH17', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'TEINH18', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'DEINH2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'DEINH1', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'DEINH6', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'MEINH13', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'MEINH8', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'MEINH14', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'DEINH4', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'DEINH5', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'TEINH2', IdentifiedType: ' IS2', color: '#FAE52E'},
        // {className: 'TEINH1', IdentifiedType: ' IS2', color: '#FAE52E'},
        // {className: 'HBINH4', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'HBINH3', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'HBINH1', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'SCINH11', IdentifiedType: ' Ivy', color: '#994D91'},
        // {className: 'MEINH3', IdentifiedType: ' MGE NGF', color: '#994D91'},
        // {className: 'MEINH4', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        // {className: 'DEINH3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH5', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH12', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH11', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH9', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH10', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'MEINH6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'HBINH6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'HBINH2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SCGLU8', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SCGLU9', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SCGLU7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SCGLU2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SCGLU3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SCGLU4', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'SCGLU6', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'SCGLU5', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'SCINH5', IdentifiedType: ' O/LM', color: '#008FCC'},
        // {className: 'SCINH6', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'SCINH7', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'HBINH9', IdentifiedType: ' O-Bi', color: '#0070AD'},
        // {className: 'SCINH2', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'SCINH4', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'SCINH3', IdentifiedType: ' PC', color: '#00FF00'},
        // {className: 'SCINH10', IdentifiedType: ' PC Other1', color: '#73E500'},
        // {className: 'SCINH9', IdentifiedType: ' PC Other2', color: '#73E500'},
        // {className: 'SCINH8', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        // {className: 'TEINH3', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        // {className: 'OBDOP1', IdentifiedType: ' Trilaminar', color: '#1F663B'},
        // {className: 'HYPEP8', IdentifiedType: ' Unidentified', color: '#A6A6A6'},
        // {className: 'ABC', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'VLMC2', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'VLMC1', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        // {className: 'VSMCA', IdentifiedType: ' Backprojection', color: '#3DCCFF'},
        // {className: 'PER3', IdentifiedType: ' Basket', color: '#7757FA'},
        // {className: 'VECA', IdentifiedType: ' Basket', color: '#7757FA'},
        // {className: 'PER2', IdentifiedType: ' Bistratified', color: '#5938DB'},
        // {className: 'PER1', IdentifiedType: ' Bistratified', color: '#5938DB'},
        // {className: 'VECV', IdentifiedType: ' Cck Calb1/Slc17a8*', color: '#FF0000'},
        // {className: 'VECC', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'MGL1', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'MGL2', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        // {className: 'MGL3', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'PVM2', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'PVM1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'SCHW', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'SATG2', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        // {className: 'SATG1', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'ACBG', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'ACOB', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        // {className: 'ACTE1', IdentifiedType: ' Cck Vip Cxcl14+', color: '#996E00'},
        // {className: 'ACTE2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'ACNT1', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'ACNT2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        // {className: 'ACMB', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'EPEN', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'EPSC', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'CHOR', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        // {className: 'SYNOR3', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'SYNOR2', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'SYNOR1', IdentifiedType: ' IS1', color: '#BDA800'},
        // {className: 'SYNOR4', IdentifiedType: ' IS2', color: '#FAE52E'},
        // {className: 'SYNOR5', IdentifiedType: ' IS2', color: '#FAE52E'},
        // {className: 'SYCHO2', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'SYCHO1', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'PSPEP1', IdentifiedType: ' IS3', color: '#DBC70F'},
        // {className: 'PSPEP3', IdentifiedType: ' Ivy', color: '#994D91'},
        // {className: 'PSPEP2', IdentifiedType: ' MGE NGF', color: '#994D91'},
        // {className: 'PSPEP4', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        // {className: 'PSPEP5', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSPEP6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSPEP7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSPEP8', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNF2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNF3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNF1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNP1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNP3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNP2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNP5', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNP4', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        // {className: 'PSNP6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},


        // I added this
        {className: 'Other', IdentifiedType: 'Other', colorGroup: 'Other', color: '#C0C0C0'},
=======
        
        {className: 'n00_Pam/Nnat', IdentifiedType: ' n00_Pam/Nnat', color: '#7757FA'},
        {className: 'n01_Foxp2/Cck', IdentifiedType: ' n01_Foxp2/Cck', color: '#EA249E'},
        {className: 'n02_Hmcn1/Cartpt', IdentifiedType: ' n02_Hmcn1/Cartpt', color: '#F6BE82'},
        {className: 'n03_Tac1/Abi3bp', IdentifiedType: ' n03_Tac1/Abi3bp', color: '#655F21'},
        {className: 'n04_Gpc5', IdentifiedType: ' n04_Gpc5', color: '#97B667'},
        {className: 'n05_Zfp804b', IdentifiedType: ' n05_Zfp804b', color: '#E4D74D'},
        {className: 'n06_Chst9/Zfhx3', IdentifiedType: ' n06_Chst9/Zfhx3', color: '#5938DB'},
        {className: 'n07_Gm32647', IdentifiedType: ' n07_Gm32647', color: '#D096A9'},
        {className: 'n08_Col11a1/Nfib', IdentifiedType: ' n08_Col11a1/Nfib', color: '#CC8C20'},
        {className: 'n09_Adarb2/Prlr', IdentifiedType: ' n09_Adarb2/Prlr', color: '#ECDADF'},
        {className: 'n10_Penk/Col9a1', IdentifiedType: ' n10_Penk/Col9a1', color: '#FE032E'},
        {className: 'n11_Ntng1/Vav3', IdentifiedType: ' n11_Ntng1/Vav3', color: '#ED6623'},
        {className: 'n12_Tac1/Epha3', IdentifiedType: ' n12_Tac1/Epha3', color: '#A3084C'},
        {className: 'n13_Sst', IdentifiedType: ' n13_Sst', color: '#880BF3'},
        {className: 'n14_Hcn1', IdentifiedType: ' n14_Hcn1', color: '#345170'},
        {className: 'n15_Calca/Pou6f2', IdentifiedType: ' n15_Calca/Pou6f2', color: '#703824'},
        {className: 'n16_Cpne9/Col27a1', IdentifiedType: ' n16_Cpne9/Col27a1', color: '#3350EE'},
        {className: 'n17_Pcdh15/Tcf4', IdentifiedType: ' n17_Pcdh15/Tcf4', color: '#3DCCFF'},
        {className: 'n18_Nefm/Rreb1', IdentifiedType: ' n18_Nefm/Rreb1', color: '#996E00'},
        {className: 'n19_Pde11a', IdentifiedType: ' n19_Pde11a', color: '#DB66C2'},
        {className: 'n20_Adarb2/Epha3', IdentifiedType: ' n20_Adarb2/Epha3', color: '#FAEC3B'},
        {className: 'n21_Ttn', IdentifiedType: ' n21_Ttn', color: '#1FADEB'},
        {className: 'n22_Slc32a1/Foxp2', IdentifiedType: ' n22_Slc32a1/Foxp2', color: '#BF0153'},
        {className: 'n23_Slc5a7/Chat', IdentifiedType: ' n23_Slc5a7/Chat', color: '#FAE52E'},
        {className: 'n24_Slc18a2/Th', IdentifiedType: ' n24_Slc18a2/Th', color: '#BDA800'},
        {className: 'n25_Il1rapl2', IdentifiedType: ' n25_Il1rapl2', color: '#220327'},
        {className: 'n26_Gm28526', IdentifiedType: ' n26_Gm28526', color: '#FF00E6'},
        {className: 'n27_4931429P17Rik/Cdh23', IdentifiedType: ' n27_4931429P17Rik/Cdh23', color: '#CD3F6A'},
        {className: 'n28_Col11a1/Zfhx3', IdentifiedType: ' n28_Col11a1/Zfhx3', color: '#6D8C8F'},
        {className: 'n29_Gm11867/Naaladl2', IdentifiedType: ' n29_Gm11867/Naaladl2', color: '#9906A2'},
        {className: 'n30_Nts/Col5a2', IdentifiedType: ' n30_Nts/Col5a2', color: '#DBC70F'},
        {className: 'n31_Nps/Qrfpr', IdentifiedType: ' n31_Nps/Qrfpr', color: '#D59C55'},
        {className: 'n32_Tnc/Rreb1', IdentifiedType: ' n32_Tnc/Rreb1', color: '#510441'},
        {className: 'n33_Prph/Piezo2', IdentifiedType: ' n33_Prph/Piezo2', color: '#FF00E6'},
        {className: 'Astro1', IdentifiedType: ' Astro1', color: '#44ED5A'},
        {className: 'Astro2', IdentifiedType: ' Astro2', color: '#44ED5A'},
        {className: 'Astro3', IdentifiedType: ' Astro3', color: '#44ED5A'},
        {className: 'Oligo1', IdentifiedType: ' Oligo1', color: '#1E6EE3'},
        {className: 'Oligo2', IdentifiedType: ' Oligo2', color: '#1E6EE3'},
        {className: 'Oligo3', IdentifiedType: ' Oligo3', color: '#1E6EE3'},
        {className: 'OPCs1', IdentifiedType: ' OPCs1', color: '#4448DC'},
        {className: 'OPCs2', IdentifiedType: ' OPCs2', color: '#4448DC'},
        {className: 'VECs/Pericyte', IdentifiedType: ' VECs/Pericyte', color: '#FFC0CB'},
        {className: 'PVM/Micro', IdentifiedType: ' PVM/Micro', color: '#FF00FF'},
        {className: 'Ependymocyte', IdentifiedType: ' Ependymocyte', color: '#FFFFFF'},
        {className: 'CPE_cells', IdentifiedType: ' CPE_cells', color: '#FFA07A'},
        {className: 'VLMCs1', IdentifiedType: ' VLMCs1', color: '#220327'},
        {className: 'VLMCs2', IdentifiedType: ' VLMCs2', color: '#220327'},
        {className: 'VLMCs3', IdentifiedType: ' VLMCs3', color: '#220327'},
        {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},
        {className: 'Other', IdentifiedType: 'Other', colorGroup: 'Other', color: '#A9B7BF'},
>>>>>>> def54c345d98235c3c3045b3a000e5a03404fa42


    ];

    return out
}